export const KAFKA_TOPICS = {
  AUTH: {
    REGISTER: 'odi.auth.register',
    LOGIN: 'odi.auth.login',
    VALIDATE_TOKEN: 'odi.auth.validate-token',
    GET_PREFERENCES: 'odi.auth.get-preferences',
    UPDATE_PREFERENCES: 'odi.auth.update-preferences',
    RESULT: 'odi.auth.result',
  },
  GAME: {
    CREATE: 'odi.game.create',
    UPDATE_STATUS: 'odi.game.update-status',
    PHASE_ADVANCE: 'odi.game.phase-advance',
    JOIN: 'odi.game.join',
    LEAVE: 'odi.game.leave',
    DELETE: 'odi.game.delete',
    RESOLVE_INVITE: 'odi.game.resolve-invite',
    BOARD_LIST: 'odi.game.board-list',
    LIST: 'odi.game.list',
    RESULT: 'odi.game.result',
    BOT_CONTEXT_LIST: 'odi.game.bot-context-list',
    BOT_CONTEXT_UPSERT: 'odi.game.bot-context-upsert',
    BOT_CONTEXT_DELETE: 'odi.game.bot-context-delete',
    SHARED_CONTEXT_UPSERT: 'odi.game.shared-context-upsert',
    SHARED_CONTEXT_DELETE: 'odi.game.shared-context-delete',
  },
  CHAT: {
    SEND: 'odi.chat.send',
    EDIT: 'odi.chat.edit',
    DELETE: 'odi.chat.delete',
    HISTORY: 'odi.chat.history',
    RESULT: 'odi.chat.result',
  },
  REFLECTION: {
    SAVE: 'odi.reflection.save',
    LIST: 'odi.reflection.list',
  },
  AI: {
    GENERATE: 'odi.ai.generate',
    GENERATE_REFLECTION: 'odi.ai.generate-reflection',
    TEST_CHAT: 'odi.ai.test-chat',
    ANALYZE_EMOTION: 'odi.ai.analyze-emotion',
    CHANGE_STRATEGY: 'odi.ai.change-strategy',
    STOP_STREAM: 'odi.ai.stop-stream',
    OLLAMA_MODELS: 'odi.ai.ollama-models',
    RESULT: 'odi.ai.result',
  },
  EVENTS: {
    SESSION: 'odi.events.session',
    CHAT: 'odi.events.chat',
    CHAT_STREAM: 'odi.events.chat-stream',
    REFLECTION_STREAM: 'odi.events.reflection-stream',
    REFLECTION: 'odi.events.reflection',
    EMOTION: 'odi.events.emotion',
    PHASE: 'odi.events.phase',
  },
} as const;
